CREATE DATABASE BookShop
use BookShop
CREATE TABLE Section (
ID INT NOT NULL,
SName VARCHAR(50) NOT NULL
PRIMARY KEY (ID)
);


CREATE TABLE Publisher (
ID INT NOT NULL,
Publisher_Name VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Item(
ID INT NOT NULL,
Publisher_ID INT, 
FOREIGN KEY (Publisher_ID) REFERENCES Publisher (ID)  ON UPDATE CASCADE,
PRIMARY KEY (ID)
);

CREATE TABLE CD (
Item_ID INT NOT NULL, 
FOREIGN KEY (Item_ID) REFERENCES Item(ID) ON DELETE CASCADE ON UPDATE CASCADE ,
CD_Name VARCHAR(50) NOT NULL,
Section_ID INT, 
FOREIGN KEY (Section_ID)  REFERENCES Section(ID)  ON UPDATE CASCADE,
PRIMARY KEY (Item_ID)
);

CREATE TABLE Author (
ID INT NOT NULL,
Author_Name VARCHAR NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Written (
Item_ID INT NOT NULL,
FOREIGN KEY (Item_ID) REFERENCES Item (ID) ON DELETE CASCADE ON UPDATE CASCADE ,
Author_ID INT, 
FOREIGN KEY (Author_ID) REFERENCES Author (ID) ON UPDATE CASCADE,
Title VARCHAR(75) NOT NULL,
NumberOfPages INT,
Released_Date DATE,
Book_Flag INT,
Magazine_Flag INT,
PRIMARY KEY (Item_ID),
Section_ID INT,
FOREIGN KEY (Section_ID) REFERENCES Section (ID)  ON UPDATE CASCADE,
);



CREATE TABLE Member
(
	SSN INT NOT NULL,
	First_Name VARCHAR(50) NOT NULL,
	Last_Name VARCHAR(50),
	Phone VARCHAR(20),
	End_Membership_Date DATE,
	Age INT,
	Adr VARCHAR(120),
	PRIMARY KEY (SSN)
);


CREATE TABLE Borrows (
SSN INT NOT NULL,
FOREIGN KEY (SSN) REFERENCES Member (SSN) ON DELETE CASCADE ON UPDATE CASCADE,
Item_ID INT NOT NULL,
FOREIGN KEY (Item_ID) REFERENCES Item (ID) ON DELETE CASCADE ON UPDATE CASCADE ,
Borrow_Date DATE NOT NULL,
Return_Date DATE,

PRIMARY KEY (SSN,Item_ID)
);
